### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by Cardoza2** [JacobChild/FlowLab_Onboarding#2]
- Good job, this is a good first draft. There is a lot of improvement in your coding and commenting. This is aided by the fact that you put text blocks in between the code blocks. 
- Typically when you're writing commits, you want to write a short descriptive statement of what was done since the last commit. Some of your commit messages were better than others. For instance, "worked on Eppler Data" is way better than "finished/not graded" or "Making progress!". Even better would be something like "added script to generate Eppler airfoil polars". 
- Typically you'll want to get rid of files that were experimental (i.e. where you were learning how to do something). That doesn't mean that you shouldn't leave behind a paper trail of how to do things, or how to figure out things. But it is good practice to transform that into a demo. That... or some tests to make sure your codes work properly. 
- We've already talked about ways that you could better communicate the error by plotting it on several different plots, or using multiple Y axes (see [here](https://goropikari.github.io/PlotsGallery.jl/src/two_y_axis.html#:~:text=Julia%20Plots%20Gallery%20Two%20y%20axis%20plot%20%23,plot%21%28twinx%28%29%2C%20randn%28100%29%2A10%2C%20c%3D%3Ared%2C%20ylabel%3D%22y2%22%2C%20leg%3D%3Abottomright%2C%20size%3D%28600%2C%20400%29%29%20plot%21%28right_bottom%3D10mm%29))
- You could use inline math (like so $C_t$) to make your talk about coefficients and other math concepts more clear. 
- There are some grammar errors in your discussion that obscure your meaning. Reading through your work aloud would be beneficial. 
- In general, your discussion needs more depth. While you are beginning to touch on important relationships, you need more depth. Your error discussion was separated from when you pointed out the error on the plots. I wanted more understanding of why there might be error then. Additionally, you barely touched on important issues like general performance. When would the performance be great? Why? Why would having better airfoil data make CCBlade give better predictions? 
- Finally, you know the advance ratio. You know the rpm. That means you can easily calculate the freestream velocity. Which means you can estimate the Reynolds number. Even if you don't want to go back and recomplete the XFoil simulations, you need to do the math and point out the differences. Reach out to me if you don't know how to do this.

**Comment by JacobChild** [comment]
1. Thanks
2. Noted
3. Done- I got rid of one file and put the others in a folder called ArchivesFromTutorial
4. I ended up making the error the third plot as I didn't really like how it looked with two y-axis, and using twinx() also presented other problems (ylabels from the two plots overlapping, and the bar graph covering the other data etc...)
5. I forgot about that. I changed what I saw and as I write more will try to remember that
6-8 still working

**Comment by Cardoza2** [comment]
I apologize at taking such a long time to respond to this. I like the increase of depth. Additionally, I feel like the organization is much better; much more clear. One thing to note, is it appears you wrote your discussion, and then the plots might have changed, because some things that you point out in your discussion don't quite match the plots. As always, it could benefit from more polishing. Go ahead and close this issue.
